// Scene Object Definitions

so_row[1]=0; so_col[1]=1; StrCpy(so_desc+(1*SO_MAX_DESC), "Diet Shasta Bottle");
so_row[2]=0; so_col[2]=2; StrCpy(so_desc+(2*SO_MAX_DESC), "Chef Boyardee");
so_row[3]=0; so_col[3]=3; StrCpy(so_desc+(3*SO_MAX_DESC), "Platinum Kilogram");
so_row[4]=0; so_col[4]=4; StrCpy(so_desc+(4*SO_MAX_DESC), "Gold Key");
so_row[5]=1; so_col[5]=1; StrCpy(so_desc+(5*SO_MAX_DESC), "Plate of Nuggies");
so_row[6]=1; so_col[6]=2; StrCpy(so_desc+(6*SO_MAX_DESC), "Bars of Soap"); 
so_row[7]=1; so_col[7]=3; StrCpy(so_desc+(7*SO_MAX_DESC), "Intel Xeon E7 CPU");
