#!/usr/bin/python3

# Erythros log file viewer for VirtualBox
# Usage: Execute this script in VM/Logs folder to view formatted system log output.

import os
import time
import subprocess
import select

os.system('clear')

f = subprocess.Popen(['tail','-F','VBox.log'],
        stdout=subprocess.PIPE,stderr=subprocess.PIPE)
p = select.poll()
p.register(f.stdout)

while True:
    if p.poll(1):
        line = f.stdout.readline()
        log_line = line.decode().split('VMMDev: Guest Log: ')
        if len(log_line) > 1:
            log_line[1] = log_line[1].strip()
            out_line = ''
            i = 0
            in_dollar = False
            while i < len(log_line[1]):
                if log_line[1][i] == "$":
                    if not in_dollar:
                        in_dollar = True
                    else:
                        in_dollar = False
                else:
                    if not in_dollar:
                        out_line += log_line[1][i]
                i += 1
            print(out_line)
